import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface MeetingData {
  title: string;
  date: string;
  duration: string;
  attendees: string[];
  agenda: string[];
  keyDecisions: Array<{ title: string; description: string; outcome: string }>;
  actionItems: Array<{
    title: string;
    assignee: string;
    deadline: string;
    priority: string;
    status: string;
  }>;
  transcript?: string;
}

export function generateMeetingReport(data: MeetingData): void {
  const doc = new jsPDF();
  let yPos = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(6, 182, 212); // Cyan
  doc.text('MEETING MINUTES REPORT', 105, yPos, { align: 'center' });
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Synapse Enterprise Intelligence Platform', 105, yPos, { align: 'center' });
  
  yPos += 15;

  // Meeting Info Box
  doc.setDrawColor(6, 182, 212);
  doc.setLineWidth(0.5);
  doc.rect(15, yPos, 180, 35);
  
  yPos += 8;
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('Meeting Details', 20, yPos);
  
  yPos += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Title: ${data.title}`, 20, yPos);
  
  yPos += 6;
  doc.text(`Date: ${data.date}`, 20, yPos);
  
  yPos += 6;
  doc.text(`Duration: ${data.duration}`, 20, yPos);
  
  yPos += 6;
  doc.text(`Attendees: ${data.attendees.join(', ')}`, 20, yPos);
  
  yPos += 15;

  // Agenda
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(6, 182, 212);
  doc.text('Meeting Agenda', 15, yPos);
  
  yPos += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  
  data.agenda.forEach((item, index) => {
    doc.text(`${index + 1}. ${item}`, 20, yPos);
    yPos += 6;
  });
  
  yPos += 5;

  // Key Decisions
  if (data.keyDecisions && data.keyDecisions.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(6, 182, 212);
    doc.text('Key Decisions', 15, yPos);
    
    yPos += 10;

    data.keyDecisions.forEach((decision, index) => {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.text(`${index + 1}. ${decision.title}`, 20, yPos);
      
      yPos += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      const splitDescription = doc.splitTextToSize(decision.description, 170);
      doc.text(splitDescription, 25, yPos);
      yPos += splitDescription.length * 5;
      
      doc.setTextColor(0, 150, 0);
      doc.text(`Outcome: ${decision.outcome}`, 25, yPos);
      yPos += 8;
    });
  }

  // Action Items Table
  if (data.actionItems && data.actionItems.length > 0) {
    if (yPos > 200) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(6, 182, 212);
    doc.text('Action Items', 15, yPos);
    
    yPos += 7;

    const tableData = data.actionItems.map((item) => [
      item.title,
      item.assignee,
      item.deadline,
      item.priority,
      item.status,
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Task', 'Assignee', 'Deadline', 'Priority', 'Status']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [6, 182, 212],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10,
      },
      bodyStyles: {
        fontSize: 9,
        textColor: [0, 0, 0],
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },
      columnStyles: {
        0: { cellWidth: 60 },
        1: { cellWidth: 35 },
        2: { cellWidth: 30 },
        3: { cellWidth: 25 },
        4: { cellWidth: 25 },
      },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Synapse Enterprise Intelligence | Page ${i} of ${pageCount}`,
      105,
      290,
      { align: 'center' }
    );
    doc.text(
      `Report Date: ${new Date().toLocaleDateString()}`,
      105,
      285,
      { align: 'center' }
    );
  }

  // Save PDF
  const fileName = `Meeting_Report_${data.title.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`;
  doc.save(fileName);
}

export function generateFraudReport(data: any): void {
  const doc = new jsPDF();
  let yPos = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(244, 63, 94); // Rose/Red
  doc.text('FRAUD ANALYSIS REPORT', 105, yPos, { align: 'center' });
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Synapse Security & Risk Intelligence', 105, yPos, { align: 'center' });
  
  yPos += 15;

  // Summary Box
  doc.setDrawColor(244, 63, 94);
  doc.setFillColor(254, 242, 242);
  doc.rect(15, yPos, 180, 25, 'FD');
  
  yPos += 8;
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 20, yPos);
  
  yPos += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Total Transactions Analyzed: ${data.totalTransactions || 'N/A'}`, 20, yPos);
  
  yPos += 6;
  doc.setTextColor(244, 63, 94);
  doc.setFont('helvetica', 'bold');
  doc.text(`Anomalies Detected: ${data.anomaliesCount || 0}`, 20, yPos);
  
  yPos += 15;

  // Flagged Transactions Table
  if (data.flaggedTransactions && data.flaggedTransactions.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(244, 63, 94);
    doc.text('Flagged Transactions', 15, yPos);
    
    yPos += 7;

    const tableData = data.flaggedTransactions.map((tx: any) => [
      tx.id || 'N/A',
      tx.amount || 'N/A',
      tx.vendor || 'N/A',
      tx.riskScore || 'N/A',
      tx.reason || 'N/A',
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Transaction ID', 'Amount', 'Vendor', 'Risk Score', 'Flag Reason']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [244, 63, 94],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10,
      },
      bodyStyles: {
        fontSize: 9,
      },
      alternateRowStyles: {
        fillColor: [254, 242, 242],
      },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Synapse Fraud Analysis System | Confidential | Page ${i} of ${pageCount}`,
      105,
      290,
      { align: 'center' }
    );
  }

  const fileName = `Fraud_Analysis_Report_${new Date().getTime()}.pdf`;
  doc.save(fileName);
}
