import { MeetingSession, MeetingParticipant } from '@/types/meeting';

export const sampleParticipants: MeetingParticipant[] = [
  {
    id: 'p-alex',
    name: 'Alex Sterling',
    designation: 'Chief Technology Officer',
    team: 'Executive Leadership & Board',
    department: 'Executive Governance & Strategy',
    employeeId: 'EMP-EXEC-001',
    email: 'alex.sterling@synapse-ai.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'p-elena',
    name: 'Elena Rostova',
    designation: 'CFO & Fraud Operations Lead',
    team: 'Cyber & Financial Fraud Ops',
    department: 'Fraud Risk & Security Forensics',
    employeeId: 'EMP-SEC-002',
    email: 'elena.rostova@synapse-ai.io',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'p-marcus',
    name: 'Marcus Vance',
    designation: 'VP of AI Product & Architecture',
    team: 'Engineering & Neural R&D',
    department: 'AI Research & Platform Architecture',
    employeeId: 'EMP-ENG-003',
    email: 'marcus.vance@synapse-ai.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'p-sophia',
    name: 'Sophia Chen',
    designation: 'Senior Financial Risk Analyst',
    team: 'Finance & Risk Analytics',
    department: 'Treasury & Risk Modeling',
    employeeId: 'EMP-FIN-004',
    email: 'sophia.chen@synapse-ai.io',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'p-david',
    name: 'David Miller',
    designation: 'Principal Legal Counsel',
    team: 'Legal, Contracts & Compliance',
    department: 'Corporate Legal & Governance',
    employeeId: 'EMP-LGL-005',
    email: 'david.miller@synapse-ai.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'p-sarah',
    name: 'Sarah Connor',
    designation: 'Lead ML Infrastructure Engineer',
    team: 'Engineering & Neural R&D',
    department: 'AI Research & Platform Architecture',
    employeeId: 'EMP-ENG-006',
    email: 'sarah.connor@synapse-ai.io',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
];

export const sampleMeetings: MeetingSession[] = [
  {
    id: 'MEET-2026-0830-EXEC',
    title: 'Executive AI Strategy & Q4 Distributed Infrastructure Sync',
    date: '2026-08-30',
    duration: '45 mins',
    organizer: 'Alex Sterling',
    organizerEmployeeId: 'EMP-EXEC-001',
    status: 'COMPLETED',
    mediaType: 'audio',
    participants: [
      sampleParticipants[0], // Alex Sterling
      sampleParticipants[1], // Elena Rostova
      sampleParticipants[2], // Marcus Vance
      sampleParticipants[4], // David Miller
    ],
    agenda: [
      'Q4 GPU cluster allocation & H100 procurement timeline',
      'Omni Fraud Anomaly detection customer rollout metrics',
      'Master Service Agreement liability caps & compliance audit',
      'Action item ownership & quarterly milestone signoff',
    ],
    utterances: [
      {
        id: 'u1',
        speaker: 'Alex Sterling',
        speakerEmployeeId: 'EMP-EXEC-001',
        speakerDesignation: 'Chief Technology Officer',
        avatarColor: 'cyan',
        startTime: '00:01',
        endTime: '02:15',
        text: 'Welcome everyone. Today we need to align on our Q4 AI roadmap and decide whether we increase our distributed GPU cluster allocation by 35% to support Synapse enterprise scale and cross-document RAG indexing.',
      },
      {
        id: 'u2',
        speaker: 'Marcus Vance',
        speakerEmployeeId: 'EMP-ENG-003',
        speakerDesignation: 'VP of AI Product & Architecture',
        avatarColor: 'purple',
        startTime: '02:18',
        endTime: '04:40',
        text: 'From a product standpoint, customer feedback on our Omni Fraud Analysis and cross-document ledger checks is exceptionally high. Enterprise clients are requesting automated voice MoM briefings and direct task delegation immediately.',
      },
      {
        id: 'u3',
        speaker: 'Elena Rostova',
        speakerEmployeeId: 'EMP-SEC-002',
        speakerDesignation: 'CFO & Fraud Operations Lead',
        avatarColor: 'emerald',
        startTime: '04:42',
        endTime: '07:10',
        text: 'I reviewed the numbers. Expanding our distributed cluster will cost approximately $42,000 monthly, but our projected enterprise ARR increase is $180,000. I move that we approve the allocation effective September 1st.',
      },
      {
        id: 'u4',
        speaker: 'David Miller',
        speakerEmployeeId: 'EMP-LGL-005',
        speakerDesignation: 'Principal Legal Counsel',
        avatarColor: 'amber',
        startTime: '07:12',
        endTime: '09:05',
        text: 'Agreed. The SOC2 Type II compliance audit report is 90% finalized. We will lock in the AES-256 data encryption keys rotation policies with the infrastructure team by Friday.',
      },
    ],
    mom: {
      meetingTitle: 'Executive AI Strategy & Q4 Distributed Infrastructure Sync',
      date: '2026-08-30',
      duration: '45 mins',
      organizer: 'Alex Sterling',
      organizerEmployeeId: 'EMP-EXEC-001',
      location: 'Executive Boardroom & Encrypted Video Bridge',
      attendees: ['Alex Sterling', 'Elena Rostova', 'Marcus Vance', 'David Miller'],
      participants: [
        sampleParticipants[0],
        sampleParticipants[1],
        sampleParticipants[2],
        sampleParticipants[4],
      ],
      executiveSummary:
        'The Executive Leadership Committee unanimously approved a 35% expansion in GPU cluster capacity ($42,000/mo) to support enterprise RAG document indexing and real-time fraud vectoring. SOC2 Type II compliance milestones remain on track for end-of-quarter certification.',
      mainThingsToDo: [
        'Deploy H100 distributed inference clusters across US-East and EU-Central',
        'Review and sign updated 2026 Master Services Agreement with $5M liability ceiling',
        'Audit high-velocity SWIFT transaction flags in Omni Fraud module',
      ],
      spokenSummary:
        'Executive Meeting Summary. The team approved expanding GPU infrastructure by 35% for $42,000 monthly, generating an estimated $180,000 in recurring revenue. 3 key action items were assigned to engineering, fraud ops, and legal.',
      agendaTopics: [
        {
          topic: 'GPU Cluster Capacity & Scaling',
          keyPoints: [
            'Current utilization at 88% capacity during peak trading hours',
            'Approved $42,000/month infrastructure expansion',
          ],
          outcomes: 'Inference nodes will scale horizontally with auto-failover.',
        },
        {
          topic: 'Omni Fraud Enterprise Expansion',
          keyPoints: [
            '14 financial institutions actively testing the anomaly detection matrix',
            'Cross-document ledger verification reduced false positives by 64%',
          ],
          outcomes: 'Fraud module promoted to production tier.',
        },
      ],
      keyDecisions: [
        'Approved 35% increase in distributed GPU capacity effective September 1st, 2026.',
        'Adopted $5,000,000 USD liability cap in all standard enterprise customer MSAs.',
        'Enforced mandatory WebAuthn hardware passkeys for all Level 4 & 5 security clearance personnel.',
      ],
      actionItems: [
        {
          id: 'act-01',
          title: 'Provision 8x H100 GPU worker nodes in US-East cluster',
          assignee: 'Marcus Vance',
          assigneeEmployeeId: 'EMP-ENG-003',
          assigneeDesignation: 'VP of AI Product & Architecture',
          assigneeTeam: 'Engineering & Neural R&D',
          deadline: '2026-09-08',
          priority: 'HIGH',
          status: 'COMPLETED',
          category: 'Engineering & Neural R&D',
          taskSummary: 'Coordinate with cloud infrastructure vendor to provision dedicated worker cluster.',
          notes: [
            {
              id: 'n-01',
              author: 'Marcus Vance',
              authorEmployeeId: 'EMP-ENG-003',
              timestamp: '2026-09-02T10:00:00Z',
              text: 'Cluster provisioned and passed initial latency benchmark (38ms P99).',
            },
          ],
        },
        {
          id: 'act-02',
          title: 'Finalize SOC2 Type II key rotation policy and legal disclosures',
          assignee: 'David Miller',
          assigneeEmployeeId: 'EMP-LGL-005',
          assigneeDesignation: 'Principal Legal Counsel',
          assigneeTeam: 'Legal, Contracts & Compliance',
          deadline: '2026-09-12',
          priority: 'HIGH',
          status: 'PENDING',
          category: 'Legal, Contracts & Compliance',
          taskSummary: 'Embed AES-256 zero-model-training warranty clauses into master template.',
          notes: [
            {
              id: 'n-02',
              author: 'David Miller',
              authorEmployeeId: 'EMP-LGL-005',
              timestamp: '2026-09-04T15:30:00Z',
              text: 'Draft shared with external auditors. Awaiting final review.',
            },
          ],
        },
        {
          id: 'act-03',
          title: 'Investigate flagged SWIFT transfer TXN-902148 ($1,450,000)',
          assignee: 'Elena Rostova',
          assigneeEmployeeId: 'EMP-SEC-002',
          assigneeDesignation: 'CFO & Fraud Operations Lead',
          assigneeTeam: 'Cyber & Financial Fraud Ops',
          deadline: '2026-09-05',
          priority: 'HIGH',
          status: 'IN_PROGRESS',
          category: 'Cyber & Financial Fraud Ops',
          taskSummary: 'Perform full forensic inspection on velocity surge and geo mismatch.',
          notes: [
            {
              id: 'n-03',
              author: 'Elena Rostova',
              authorEmployeeId: 'EMP-SEC-002',
              timestamp: '2026-09-01T11:00:00Z',
              text: 'Contacted corresponding Swiss banking partner for AML verification documents.',
            },
          ],
        },
      ],
      riskRegister: [
        {
          risk: 'Cloud compute quota exhaustion during peak market volatility',
          impact: 'MEDIUM',
          mitigation: 'Implement dynamic threshold throttling and cross-region overflow routing.',
        },
      ],
    },
  },
];
