import { TransactionRecord, FraudAnalysisSummary, RiskSeverity } from '@/types/fraud';

export const sampleTransactions: TransactionRecord[] = [
  {
    id: 'TXN-902148',
    timestamp: '2026-08-30T10:42:15Z',
    accountSender: 'ACC-881940 (Global Capital Corp)',
    senderName: 'Global Capital Corp',
    accountRecipient: 'ACC-110294 (Apex Offshore Holdings)',
    recipientName: 'Apex Offshore Holdings',
    senderLocation: 'New York, US',
    recipientLocation: 'George Town, KY (Cayman Islands)',
    country: 'Cayman Islands',
    amount: 1450000,
    currency: 'USD',
    paymentMethod: 'SWIFT International',
    merchant: 'Apex Wire Routing Bank Ltd',
    merchantCategory: 'Financial Services / Offshore Wire',
    device: 'MacBook Pro Workstation',
    deviceFingerprint: 'DEV-FP-99021-X',
    ipAddress: '185.220.101.5 (Tor Exit Node)',
    riskScore: 94,
    riskLevel: 'CRITICAL',
    severity: 'CRITICAL',
    riskReasons: [
      'Abnormal transaction velocity (5 wires in 12 minutes)',
      'High-risk offshore tax sanctuary recipient country',
      'Unrecognized VPN / Tor Exit Node IP address detected',
      'Amount exceeds 90-day baseline transfer limit by 420%',
    ],
    flagReasons: [
      'Abnormal transaction velocity (5 wires in 12 minutes)',
      'High-risk offshore tax sanctuary recipient country',
      'Unrecognized VPN / Tor Exit Node IP address detected',
      'Amount exceeds 90-day baseline transfer limit by 420%',
    ],
    status: 'FLAGGED',
    assignedInvestigator: 'Elena Rostova (EMP-SEC-002)',
    anomalyFactors: {
      velocityFactor: 8.4,
      amountAnomaly: 4.2,
      geoMismatch: true,
      knownBlacklistIP: true,
    },
    anomalyBreakdown: {
      unusualAmount: { isAnomaly: true, score: 95, details: 'Transferred $1,450,000 is 4.2x above 30-day average ($345,000).' },
      transactionVelocity: { isAnomaly: true, score: 92, details: '5 wire transfers initiated within a 12-minute interval.' },
      unusualCountry: { isAnomaly: true, score: 98, details: 'Recipient destination in Cayman Islands flagged as high-risk AML corridor.' },
      unusualDeviceOrIP: { isAnomaly: true, score: 99, details: 'Originating IP (185.220.101.5) matches known Tor exit node cluster.' },
      unusualTransactionTime: { isAnomaly: false, score: 20, details: 'Initiated during regular market operating hours.' },
      repeatedTransfers: { isAnomaly: true, score: 85, details: 'Identical structured transfer sent to related shell holding account.' },
      abnormalBehavior: { isAnomaly: true, score: 90, details: 'Beneficiary wire routing modified 4 hours prior to transaction.' },
    },
    investigationNotes: [
      {
        id: 'inv-note-01',
        authorEmployeeId: 'EMP-SEC-002',
        authorName: 'Elena Rostova',
        timestamp: '2026-08-30T11:00:00Z',
        note: 'Requested beneficial ownership documentation and freeze request submitted to intermediary clearing bank.',
        actionTaken: 'FLAGGED & ESCALATED',
      },
    ],
  },
  {
    id: 'TXN-881923',
    timestamp: '2026-08-30T09:15:30Z',
    accountSender: 'ACC-441029 (Starlight Tech Systems)',
    senderName: 'Starlight Tech Systems',
    accountRecipient: 'ACC-992014 (Nexus Data Solutions)',
    recipientName: 'Nexus Data Solutions',
    senderLocation: 'London, UK',
    recipientLocation: 'Zurich, CH',
    country: 'Switzerland',
    amount: 480000,
    currency: 'USD',
    paymentMethod: 'Wire Transfer',
    merchant: 'Swiss Corporate Clearing AG',
    merchantCategory: 'Software Services / Enterprise License',
    device: 'ThinkPad P1 Gen 6',
    deviceFingerprint: 'DEV-FP-33019-B',
    ipAddress: '194.26.29.110',
    riskScore: 82,
    riskLevel: 'HIGH',
    severity: 'HIGH',
    riskReasons: [
      'Rapid sequential transfer following vendor IBAN modification',
      'Mismatched IBAN routing clearing house code',
      'Off-hours corporate wire submission',
    ],
    flagReasons: [
      'Rapid sequential transfer following vendor IBAN modification',
      'Mismatched IBAN routing clearing house code',
    ],
    status: 'UNDER_INVESTIGATION',
    assignedInvestigator: 'Elena Rostova (EMP-SEC-002)',
    anomalyFactors: {
      velocityFactor: 4.1,
      amountAnomaly: 2.5,
      geoMismatch: true,
      knownBlacklistIP: false,
    },
    anomalyBreakdown: {
      unusualAmount: { isAnomaly: true, score: 80, details: 'Amount ($480,000) exceeds quarterly software license budget.' },
      transactionVelocity: { isAnomaly: true, score: 75, details: 'Second transfer in 24 hours to newly registered vendor entity.' },
      unusualCountry: { isAnomaly: false, score: 30, details: 'UK to Switzerland standard corporate corridor.' },
      unusualDeviceOrIP: { isAnomaly: true, score: 84, details: 'Subnet IP mismatch with registered vendor accounting portal.' },
      unusualTransactionTime: { isAnomaly: true, score: 78, details: 'Submitted at 03:15 AM local sender time.' },
      repeatedTransfers: { isAnomaly: false, score: 25, details: 'Single wire transfer.' },
      abnormalBehavior: { isAnomaly: true, score: 88, details: 'Vendor bank account changed via email ticket 24h prior.' },
    },
    investigationNotes: [
      {
        id: 'inv-note-02',
        authorEmployeeId: 'EMP-FIN-004',
        authorName: 'Sophia Chen',
        timestamp: '2026-08-30T09:45:00Z',
        note: 'Cross-checking with vendor procurement team to verify whether invoice change was authorized.',
      },
    ],
  },
  {
    id: 'TXN-773019',
    timestamp: '2026-08-30T08:50:11Z',
    accountSender: 'ACC-119203 (Vanguard Logistics)',
    senderName: 'Vanguard Logistics',
    accountRecipient: 'ACC-552019 (Fuel Logistics Direct)',
    recipientName: 'Fuel Logistics Direct',
    senderLocation: 'Chicago, US',
    recipientLocation: 'Houston, US',
    country: 'United States',
    amount: 85200,
    currency: 'USD',
    paymentMethod: 'ACH Transfer',
    merchant: 'FleetFuel Commercial Systems',
    merchantCategory: 'Freight & Fleet Operations',
    device: 'Dell Workstation',
    deviceFingerprint: 'DEV-FP-11029-A',
    ipAddress: '64.233.160.1',
    riskScore: 28,
    riskLevel: 'LOW',
    severity: 'LOW',
    riskReasons: ['Standard recurring supplier payment with minor timing variance.'],
    flagReasons: ['Standard recurring supplier payment'],
    status: 'VERIFIED',
    anomalyFactors: {
      velocityFactor: 1.1,
      amountAnomaly: 1.0,
      geoMismatch: false,
      knownBlacklistIP: false,
    },
    anomalyBreakdown: {
      unusualAmount: { isAnomaly: false, score: 15, details: 'Within 5% of monthly diesel fuel fleet baseline.' },
      transactionVelocity: { isAnomaly: false, score: 10, details: 'Standard bi-weekly schedule.' },
      unusualCountry: { isAnomaly: false, score: 5, details: 'Domestic US transfer.' },
      unusualDeviceOrIP: { isAnomaly: false, score: 10, details: 'Registered HQ static IP.' },
      unusualTransactionTime: { isAnomaly: false, score: 12, details: 'Submitted at 08:50 AM business hours.' },
      repeatedTransfers: { isAnomaly: false, score: 10, details: 'Regular recurring schedule.' },
      abnormalBehavior: { isAnomaly: false, score: 10, details: 'Verified vendor account on file since 2022.' },
    },
    investigationNotes: [],
  },
  {
    id: 'TXN-661092',
    timestamp: '2026-08-30T07:22:45Z',
    accountSender: 'ACC-339201 (Horizon BioHealth)',
    senderName: 'Horizon BioHealth',
    accountRecipient: 'ACC-882194 (CyberShield Security)',
    recipientName: 'CyberShield Security',
    senderLocation: 'San Francisco, US',
    recipientLocation: 'Tel Aviv, IL',
    country: 'Israel',
    amount: 230000,
    currency: 'USD',
    paymentMethod: 'SWIFT International',
    merchant: 'Bank Leumi Corporate FX',
    merchantCategory: 'Cybersecurity Infrastructure',
    device: 'MacBook Air M2',
    deviceFingerprint: 'DEV-FP-77210-C',
    ipAddress: '82.102.21.99',
    riskScore: 68,
    riskLevel: 'MEDIUM',
    severity: 'MEDIUM',
    riskReasons: [
      'Cross-border transaction with newly onboarded international supplier',
      'Amount close to single-signoff approval threshold ($250,000)',
    ],
    flagReasons: [
      'Cross-border transaction with newly onboarded international supplier',
      'Amount close to single-signoff approval threshold ($250,000)',
    ],
    status: 'REVIEWED',
    assignedInvestigator: 'Elena Rostova (EMP-SEC-002)',
    anomalyFactors: {
      velocityFactor: 2.2,
      amountAnomaly: 1.8,
      geoMismatch: true,
      knownBlacklistIP: false,
    },
    anomalyBreakdown: {
      unusualAmount: { isAnomaly: false, score: 55, details: 'Amount within approved MSA budget cap.' },
      transactionVelocity: { isAnomaly: false, score: 35, details: 'First invoice under contract.' },
      unusualCountry: { isAnomaly: true, score: 65, details: 'Cross-border international transfer to Israel.' },
      unusualDeviceOrIP: { isAnomaly: false, score: 25, details: 'Authorized corporate IP.' },
      unusualTransactionTime: { isAnomaly: false, score: 30, details: 'Submitted at 07:22 AM.' },
      repeatedTransfers: { isAnomaly: false, score: 10, details: 'Single milestone payment.' },
      abnormalBehavior: { isAnomaly: false, score: 40, details: 'Matches approved MSA DOC-2026-MSA-01.' },
    },
    investigationNotes: [
      {
        id: 'inv-note-03',
        authorEmployeeId: 'EMP-SEC-002',
        authorName: 'Elena Rostova',
        timestamp: '2026-08-30T08:00:00Z',
        note: 'Verified against signed contract. Approved by CFO.',
        actionTaken: 'REVIEWED & CLEARED',
      },
    ],
  },
  {
    id: 'TXN-550183',
    timestamp: '2026-08-30T06:10:00Z',
    accountSender: 'ACC-771920 (Aegis Treasury Holding)',
    senderName: 'Aegis Treasury Holding',
    accountRecipient: 'ACC-331092 (Solana Liquidity Gateway)',
    recipientName: 'Solana Liquidity Gateway',
    senderLocation: 'New York, US',
    recipientLocation: 'Singapore, SG',
    country: 'Singapore',
    amount: 890000,
    currency: 'USD',
    paymentMethod: 'Cryptocurrency Gateway',
    merchant: 'Decentralized Treasury Bridge',
    merchantCategory: 'Digital Asset Liquidity',
    device: 'Unknown Linux Server',
    deviceFingerprint: 'DEV-FP-00921-Z',
    ipAddress: '45.154.255.81',
    riskScore: 96,
    riskLevel: 'CRITICAL',
    severity: 'CRITICAL',
    riskReasons: [
      'Unscheduled cryptocurrency liquidity transfer exceeding risk parameters',
      'Unknown Linux automated daemon fingerprint',
      'High-risk decentralized bridge without dual corporate multi-sig signoff',
    ],
    flagReasons: [
      'Unscheduled cryptocurrency liquidity transfer exceeding risk parameters',
      'Unknown Linux automated daemon fingerprint',
    ],
    status: 'BLOCKED',
    assignedInvestigator: 'Elena Rostova (EMP-SEC-002)',
    anomalyFactors: {
      velocityFactor: 9.1,
      amountAnomaly: 5.0,
      geoMismatch: true,
      knownBlacklistIP: true,
    },
    anomalyBreakdown: {
      unusualAmount: { isAnomaly: true, score: 98, details: '$890,000 crypto wire exceeds treasury single limit.' },
      transactionVelocity: { isAnomaly: true, score: 94, details: 'Sudden high-volume drain attempt.' },
      unusualCountry: { isAnomaly: true, score: 85, details: 'Offshore gateway routing.' },
      unusualDeviceOrIP: { isAnomaly: true, score: 98, details: 'Unknown server fingerprint with unverified SSH session.' },
      unusualTransactionTime: { isAnomaly: true, score: 90, details: 'Submitted at 06:10 AM Sunday morning.' },
      repeatedTransfers: { isAnomaly: true, score: 92, details: 'Repeated micro-probes prior to large transfer.' },
      abnormalBehavior: { isAnomaly: true, score: 99, details: 'No prior multi-sig approval found in governance logs.' },
    },
    investigationNotes: [
      {
        id: 'inv-note-04',
        authorEmployeeId: 'EMP-SEC-002',
        authorName: 'Elena Rostova',
        timestamp: '2026-08-30T06:25:00Z',
        note: 'Automated circuit breaker triggered. Account quarantined and wire cancelled.',
        actionTaken: 'BLOCKED BY SOC',
      },
    ],
  },
];

export const sampleFraudSummary: FraudAnalysisSummary = {
  id: 'FSUM-2026-AUG',
  datasetName: 'August 2026 Global Wire & Treasury Ledger.csv',
  processedAt: '2026-08-30T12:00:00Z',
  totalTransactions: 142,
  totalVolumeUSD: 31250000,
  flaggedCount: 3,
  flaggedVolumeUSD: 2820000,
  averageRiskScore: 48.2,
  criticalAlertCount: 2,
  highRiskCount: 1,
  mediumRiskCount: 1,
  lowRiskCount: 138,
  topRiskCategories: [
    { category: 'Offshore Tax Sanctuary Wires', count: 4 },
    { category: 'Tor / Proxy IP Routing', count: 3 },
    { category: 'Velocity Limit Breach', count: 6 },
    { category: 'Unapproved Vendor Bank Modification', count: 2 },
  ],
  locationRiskMap: [
    { country: 'Cayman Islands', count: 2, riskScore: 94 },
    { country: 'Singapore', count: 1, riskScore: 96 },
    { country: 'Switzerland', count: 3, riskScore: 82 },
    { country: 'United States', count: 128, riskScore: 28 },
    { country: 'Israel', count: 8, riskScore: 68 },
  ],
};
